name:                imageConverter
version:             0.1.0.0
github:              "ruzen42/imageConverter"
license:             BSD-3-Clause
author:              "Jaroslav Mihajlenko"
maintainer:          "malledeferlive@gmail.com"
copyright:           "2025 Jaroslav Mihajlenko"

extra-source-files:
- README.md
- CHANGELOG.md
synopsis:            simple image formats converter
category:            system

description:         simple image formats converter

dependencies:
- base >= 4.12.0.0 && < 4.23
- JuicyPixels >= 3.3.8 && <= 3.3.9
- filepath >= 1.5.2.0 && <= 1.5.4.0
- optparse-applicative >= 0.18.1.0 && <= 0.19.0.0

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  imageConverter-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - imageConverter

tests:
  imageConverter-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - imageConverter
